### ISSUE TITLE
Panic during wasm-pack build

### ISSUE THREAD

**Issue by chanks** [rustwasm/wasm-pack#641]
## 🐛 Bug description
I'm on a current clone (ref `d382ad72`) of the `wasm-bindgen` repo, trying to run `wasm-pack build` in the `dom` example, and I'm getting a panic. I'm a rust/wasm newbie, it's very possible that I'm doing something wrong, but I hope this is very easy to reproduce.

#### 🤔 Expected Behavior
What should have happened?
Expected it to build the example successfully.

#### 👟 Steps to reproduce
```
chris@ada:~/wasm-bindgen/examples/dom$ wasm-pack --version
wasm-pack 0.8.1
chris@ada:~/wasm-bindgen/examples/dom$ rustc --version
rustc 1.34.0 (91856ed52 2019-04-10)
chris@ada:~/wasm-bindgen/examples/dom$ wasm-pack build
[INFO]: Checking for the Wasm target...
[INFO]: Compiling to Wasm...
    Finished release [optimized] target(s) in 0.10s
[INFO]: Installing wasm-bindgen...
thread 'main' panicked at 'index 114 out of range for slice of length 34', src/libcore/slice/mod.rs:2413:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
Error: Running the wasm-bindgen CLI
Caused by: failed to execute `wasm-bindgen`: exited with exit code: 101
chris@ada:~/wasm-bindgen/examples/dom$ RUST_BACKTRACE=1 wasm-pack build
[INFO]: Checking for the Wasm target...
[INFO]: Compiling to Wasm...
    Finished release [optimized] target(s) in 0.10s
[INFO]: Installing wasm-bindgen...
thread 'main' panicked at 'index 114 out of range for slice of length 34', src/libcore/slice/mod.rs:2413:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::_print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::continue_panic_fmt
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::slice::slice_index_len_fail
   9: <&'src str as wasm_bindgen_cli_support::decode::Decode<'src>>::decode
  10: <alloc::vec::Vec<T> as wasm_bindgen_cli_support::decode::Decode<'src>>::decode
  11: <wasm_bindgen_cli_support::decode::Export<'a> as wasm_bindgen_cli_support::decode::Decode<'a>>::decode
  12: <alloc::vec::Vec<T> as wasm_bindgen_cli_support::decode::Decode<'src>>::decode
  13: <wasm_bindgen_cli_support::decode::Program<'a> as wasm_bindgen_cli_support::decode::Decode<'a>>::decode
  14: wasm_bindgen_cli_support::Bindgen::_generate
  15: wasm_bindgen::main
  16: std::rt::lang_start::{{closure}}
  17: std::panicking::try::do_call
  18: __rust_maybe_catch_panic
  19: std::rt::lang_start_internal
  20: main
Error: Running the wasm-bindgen CLI
Caused by: failed to execute `wasm-bindgen`: exited with exit code: 101
```

I tried running it again after a `cargo clean`, and it recompiled everything but panicked with the same error.

#### 🌍 Your environment
Include the relevant details of your environment.
wasm-pack version: 0.8.1
rustc version: 1.34.0

**Comment by clearloop** [comment]
same issue.

### Solution

**1. install your local crate**

```sh
cargo install --path  /path/to/local/wasm-bindgen
```

**2. wasm-pack with no-install mode**

```sh
wasm-pack --mode no-install
```
